from __future__ import print_function
from telesign.messaging import MessagingClient

customer_id = "#"
api_key = "#"

phone_number = "Your Contact Number"
message = "Type Msg Here"
message_type = "ARN"

messaging = MessagingClient(customer_id, api_key)
response = messaging.message(phone_number, message, message_type)

# Customer ID & Api Generated By Your Telesign Account
# Money Required for sending SMS
